### ISSUE TITLE
No module named 'verbal_expressions'

### ISSUE THREAD

**Issue by JavaProgrammerLB** [VerbalExpressions/PythonVerbalExpressions#18]
I am so glad to find this project,thank you.
I open this issue for an Error when I use this modulue.
After I executed 'pip install VerbalExpressions'  in my x64 Windows 7 PC,I got a response:"Successfully installed VerbalExpressions-0.01".But when I use "from verbalexpressions import VerEx" I got an importError:
"Traceback<most recent call last>:
  File "<stdin>", line 1, in <module>
  File "D:\Python\lib\site-packages\verbalexpressions\__init__.py", line 1, in <
module>
    from verbal_expressions import VerEx, re_escape
ImportError: No module named 'verbal_expressions'
"
How can i figure out this problem?

**Comment by scottsievert** [comment]
I fixed this problem by activating a Python 2.7 virtualenv. I'm on Python 3.5 by default.

**Comment by JavaProgrammerLB** [comment]
@scottsievert  Yes, I figured out this with your method.
