### ISSUE TITLE
Py 3.6 support

### ISSUE THREAD

**Issue by Phuket2** [VerbalExpressions/PythonVerbalExpressions#26]
I am a python newbie as well with re. That's why this lib got my attention.  I use Pythonista on iOS.  I was able to pip install the lib. It installed fine.
Pythonista runs 3.6.x or 2.7.x. 
I can run the example under 2.7, but not 3.6
So i hope you update it to be 3.6 friendly

**Comment by vtitor** [comment]
The fix is already released: https://pypi.org/project/VerbalExpressions/0.0.2/
